Corrección de typos  y adición de un texto adicional
daagonzalezgu/hyperblog pull request #1
Opened 2020-07-30 23:40 UTC by daagonzalezgu

Por favor revisar la corrección de typos =D

2020-07-30 23:42 UTC, David1915-pre commented on Blogpost.html
> +                    increíblemente aburrido, pero al
Cambio formato

2020-07-30 23:43 UTC, David1915-pre commented on Blogpost.html
> +                </p>
Me gusta. Esta parte está perfecta.

2020-07-30 23:44 UTC, David1915-pre commented
En los comentarios están los cambios a hacer. El formato pedido es el HTML5. 
Estoy atento a las novedades.

2020-07-30 23:51 UTC, David1915-pre requested changes
No usar tildes directas. Cambiar a entidades HTML

2020-07-31 00:01 UTC, daagonzalezgu commented
Cambios hechos. Por favor hacer el merge. Gracias

2020-07-31 00:04 UTC, David1915-pre approved these changes
Eso era ¡excelente!

2020-07-31 00:05 UTC, merged